package co.edu.unbosque.view;

import javax.swing.JButton;
import javax.swing.JTextArea;

public class MainPanel extends javax.swing.JPanel {

    public MainPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fileContentArea = new javax.swing.JTextArea();
        openFileBtn = new javax.swing.JButton();
        createFileBtn = new javax.swing.JButton();
        writeFileBtn = new javax.swing.JButton();
        cleanFileBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Administrador de archivo");

        fileContentArea.setBackground(new java.awt.Color(204, 204, 204));
        fileContentArea.setColumns(20);
        fileContentArea.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        fileContentArea.setForeground(new java.awt.Color(0, 0, 0));
        fileContentArea.setRows(5);
        jScrollPane1.setViewportView(fileContentArea);

        openFileBtn.setText("Abrir archivo");
        openFileBtn.setFocusable(false);
        openFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileBtnActionPerformed(evt);
            }
        });

        createFileBtn.setText("Crear archivo");
        createFileBtn.setFocusable(false);
        createFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createFileBtnActionPerformed(evt);
            }
        });

        writeFileBtn.setText("Guardar");
        writeFileBtn.setFocusable(false);

        cleanFileBtn.setText("Limpiar");
        cleanFileBtn.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(createFileBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(writeFileBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(openFileBtn)
                    .addComponent(cleanFileBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(openFileBtn)
                            .addComponent(createFileBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(writeFileBtn)
                            .addComponent(cleanFileBtn))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void openFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openFileBtnActionPerformed

    private void createFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createFileBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createFileBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cleanFileBtn;
    private javax.swing.JButton createFileBtn;
    private javax.swing.JTextArea fileContentArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton openFileBtn;
    private javax.swing.JButton writeFileBtn;
    // End of variables declaration//GEN-END:variables

    public JButton getCleanFileBtn() {
        return cleanFileBtn;
    }

    public void setCleanFileBtn(JButton cleanFileBtn) {
        this.cleanFileBtn = cleanFileBtn;
    }

    public JButton getCreateFileBtn() {
        return createFileBtn;
    }

    public void setCreateFileBtn(JButton createFileBtn) {
        this.createFileBtn = createFileBtn;
    }

    public JTextArea getFileContentArea() {
        return fileContentArea;
    }

    public void setFileContentArea(JTextArea fileContentArea) {
        this.fileContentArea = fileContentArea;
    }

    public JButton getOpenFileBtn() {
        return openFileBtn;
    }

    public void setOpenFileBtn(JButton openFileBtn) {
        this.openFileBtn = openFileBtn;
    }

    public JButton getWriteFileBtn() {
        return writeFileBtn;
    }

    public void setWriteFileBtn(JButton writeFileBtn) {
        this.writeFileBtn = writeFileBtn;
    }

    
}
